#!/bin/bash

VERSION=0.1.0

DEST=/usr/local/bin
TARGET=$PWD/jo*

RFLAG=0

function usage { 
    printf "NAME\n\t$(basename $0) - install and remove jon and jof\n\n"
    printf "SYNOPSIS\n\t./$(basename $0) [OPTION]\n\n"
    echo "DESCRIPTION"
    printf "\tInstall jon and jof either to a directory passed as an argument to the option -d or to /usr/local/bin by default.\n"
    printf "\n\tRemove scripts either from a directory passed as an argument to the option -R or from /usr/local/bin using the options -r or --remove.\n"
    printf "\n\t-d, --directory [STRING]\tInstall scripts in directory STRING\n"
    printf "\n\t-h, --help\t\t\tShow help about command line options\n"
    printf "\n\t-r\t\t\t\tRemove scripts from /usr/local/bin\n"
    printf "\n\t-v, --version\t\t\tGet version information\n"
    exit 1
}

function version { 
    echo "$(basename $0): $VERSION"
    exit 1
}

function remove { 
    for script in $TARGET; do 
	if [ $script != $PWD/$(basename $0) ]; then 
	    EXISTS=$(echo $(ls $DEST | grep $(basename $script)))
	    if [ $EXISTS ]; then 
		sudo rm $DEST/$(basename $script)
		echo "--- removing $(basename $script) from $DEST"
	    fi 
	fi 
    done
    exit 1
}

function install { 
    for script in $TARGET; do
	if [ ! $script == $PWD/$(basename $0) ]; then 
	    sudo cp $PWD/$(basename $script) $DEST/$(basename $script)
	    sudo chmod a+x $DEST/$(basename $script)	    
	    echo "--- installing $(basename $script) in $DEST"
	fi  
    done
    exit 1
}

if [ ! $1 ]; then 
    install 
else 
    if [ $1 == "--help" ]; then 
	usage
    elif [ $1 == "--remove" ]; then 
	if [ $2 ]; then 
	    DEST=$2
	fi
	remove
    elif [ $1 == "--version" ]; then 
	version
    elif [ $1 == "--directory" ]; then 
	DEST=$1
	install
    else 
	while getopts ":d:hvrR:" arg; do 
	    case "${arg}" in 
		d)
		    DEST="${OPTARG}"
		    install
		    ;;
		h)
		    usage
		    ;;
		v) 
		    version
		    ;;
		r)
		    remove
		    ;;
		R) 
		    DEST="${OPTARG}"
		    remove
		    ;;
		?) 
	    esac
	done
    fi 
fi 
