#!/bin/bash

VERSION=0.1.0

DEST=/usr/local/bin
TARGET=$PWD/jo*

if (! command -v jack_control &> /dev/null) || (! command -v a2jmidid &> /dev/null) || (! command -v qjackctl &> /dev/null); then 
    echo "Dependencies not installed."
    echo -n "Run the following:"
    printf "\n\tsudo apt install jackd2 a2jmidid qjackctl\n"
    exit 0
fi 

function usage { 
    printf "NAME\n\t$(basename $0) - install and remove jon and jof\n\n"
    printf "SYNOPSIS\n\t./$(basename $0) [OPTION]\n\n"
    echo "DESCRIPTION"
    printf "\tInstall and remove jon and jof to a directory or to /usr/local/bin by default.\n"
    printf "\n\t-d [STRING]\t\tInstall scripts in directory STRING\n"
    printf "\n\t-h, --help\t\tShow help about command line options\n"
    printf "\n\t-r, --remove\t\tRemove scripts from /usr/local/bin\n"
    printf "\n\t-R [STRING]\t\tRemove scripts from directory STRING\n"
    printf "\n\t-v, --version\t\tGet version information\n"
    exit 0
}

function version { 
    echo "$(basename $0): $VERSION"
    exit 0
}

function remove { 
    for script in $TARGET; do 
	if [ $script != $PWD/$(basename $0) ]; then 
	    EXISTS=$(echo $(ls $DEST | grep $(basename $script)))
	    if [ $EXISTS ]; then 
		sudo rm $DEST/$(basename $script)
		echo "--- removing $(basename $script) from $DEST"
	    fi 
	fi 
    done
    exit 0
}

function install { 
    for script in $TARGET; do
	if [ ! $script == $PWD/$(basename $0) ]; then 
	    sudo cp $PWD/$(basename $script) $DEST/$(basename $script)
	    sudo chmod a+x $DEST/$(basename $script)	    
	    echo "--- installing $(basename $script) in $DEST"
	fi  
    done
    exit 0
}

if [ ! $1 ]; then 
    install 
else 
    if [ $1 == "--help" ]; then 
	usage
    elif [ $1 == "--remove" ]; then 
	if [ $2 ]; then 
	    DEST=$2
	fi
	remove
    elif [ $1 == "--version" ]; then 
	version
    elif [ $1 == "--directory" ]; then 
	DEST=$1
	install
    else 
	while getopts ":d:hvrR:" arg; do 
	    case "${arg}" in 
		d)
		    DEST="${OPTARG}"
		    install
		    ;;
		h)
		    usage
		    ;;
		v) 
		    version
		    ;;
		r)
		    remove
		    ;;
		R) 
		    DEST="${OPTARG}"
		    remove
		    ;;
		?) 
	    esac
	done
    fi 
fi 
