#!/bin/bash

VERSION=0.1.0

PROG=$(basename $0)

function usage { 
    printf "NAME\n\t$PROG - A convenience script for stopping JACK, a2jmidid, and QjackCtl\n\n" 2>&1
    printf "SYNOPSIS\n\t./$PROG [OPTION] ... \n\n"
    printf "DESCRIPTION\n\t Check for and kill processes running JACK, a2jmidid, and QjackCTL"
    printf "\n\n\t-h\t\tShow help about command line options"
    printf "\n\n\t-u [STRING]\tUninstall $PROG from directory STRING"
    printf "\n\n\t-v\t\tShow version information\n"
    exit 0
}

function uninstall { 
    echo "Uninstalling $PROG"
    sudo rm /usr/local/bin/$PROG 
    exit 0
}

function version { 
    echo "$PROG: $VERSION"
    exit 0
}

while getopts ":huv" arg; do 
    case "${arg}" in 
	h) 
	    usage 
	    ;;
	u)
	    uninstall
	    ;;
	v)
	    version 
	    ;; 
    esac
done

#kill jackdbus if it is running
jackpid=$(pgrep jackdbus)
if [ "$jackpid" ]; then 
    echo "--- killing jackdbus"
    kill -9 $jackpid
fi 

#kill a2jmidi daemon if it is running
a2jpid=$(pgrep a2jmidid)
if [ "$a2jpid" ]; then 
    echo "--- killing a2jmidid"
    kill -9 $a2jpid
fi

#kill qjackctl if it is running
qjpid=$(pgrep qjackctl)
if [ "$qjpid" ]; then 
    echo "--- killing qjackctl"
    kill -9 $qjpid
fi
